Homework_1
Katerina5649/2019-2-Track-Frontend-E-Trimbach pull request #1
Opened 2019-10-06 18:33 UTC by Katerina5649

#Домашнее задание №1
Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
Реализованы функции convertBytesToHuman.js, correctSentence.js, nonUniqueElements.js и написаны к ним тесты

2019-10-07 06:37 UTC, chexex requested changes
Необходимо связать репозиторий со сборщиком (travis-ci.org)
Помогут последние слайды с первой лекции.
После того, как репозиторий будет добавлен в сборку, необходимо будет выполнить любой коммит и запушить изменения, чтобы стартануть сборку.

2019-10-07 20:19 UTC, Katerina5649 commented
Вроде добавила. Что-нибудь поменялось?

2019-10-07 20:24 UTC, chexex commented
> Вроде добавила. Что-нибудь поменялось?

Не-а. Дай ссылку на свой сборщик, пожалуйста

2019-10-09 18:31 UTC, chexex approved these changes
Функции +
Тесты +
Сборка +

Спасибо за работу,
12 баллов

2019-10-09 18:31 UTC, merged