Hm 2
Katerina5649/2019-2-Track-Frontend-E-Trimbach pull request #2
Opened 2019-10-14 20:12 UTC by Katerina5649

Домашняя работа #2
Прошу @martinkomitsky , @chexex  , @priver  проверить его
Что было сделано :
Было создана страница чата с возможностью отправки сообщений  и с сохранением в localStorage. 

PS : К сожалению есть только отдаленная схожесть с макетом. Со временем это будет исправлено.

2019-10-15 14:04 UTC, priver requested changes
Нужно выкатить на github pages

2019-10-15 14:04 UTC, priver commented on web-components/src/components/MessageForm.js
> +        const message = document.createElement("li")
нужно создать отдельный компонент для сообщения

2019-10-23 15:00 UTC, priver requested changes
Дизайн не соответствует макету

2019-10-23 15:00 UTC, priver commented on web-components/src/index.js
> +import './components/MessageForm';
не хватает импорта Message.js

2019-10-24 06:56 UTC, chexex commented
Доработать дизайн
![image](https://user-images.githubusercontent.com/16698238/67460801-92a4e580-f644-11e9-822a-d592e30c9620.png)

2019-10-27 10:10 UTC, martinkomitsky commented on .idea/workspace.xml
> +<project version="4">
в гитигноре должна быть вся папка .idea

2019-11-01 10:22 UTC, priver approved these changes
6 баллов

2019-11-01 10:22 UTC, merged